Repository aboutcode-org/vulnerablecode, pull requests merged in 2024-10, with the labels that each got.

#1603 Fix 500 Server Error with DRF browsable API and resolve blank Swagger API documentation
  requirements.txt
  setup.cfg
  vulnerabilities/api.py
  vulnerablecode/settings.py
Labels: API

#1598 Fix vers range crash
  vulnerabilities/importer.py
  vulnerabilities/improvers/default.py
  vulnerabilities/models.py
  vulnerabilities/tests/test_default_improver.py
Labels: 2-next

#1612 Segregate PackageRelatedVulnerability model to new models
  vulnerabilities/admin.py
  vulnerabilities/api.py
  vulnerabilities/api_extension.py
  vulnerabilities/import_runner.py
  vulnerabilities/improve_runner.py
  vulnerabilities/management/commands/export.py
  vulnerabilities/migrations/0070_alter_advisory_created_by_and_more.py
  vulnerabilities/migrations/0071_auto_20241007_1044.py
  vulnerabilities/migrations/0072_remove_package_vulnerabilities_and_more.py
  vulnerabilities/migrations/0073_delete_packagerelatedvulnerability.py
  vulnerabilities/models.py
  vulnerabilities/pipes/advisory.py
  vulnerabilities/tests/test_api.py
  vulnerabilities/tests/test_api_extension.py
  vulnerabilities/tests/test_example.py
  vulnerabilities/tests/test_export.py
  vulnerabilities/tests/test_fix_models.py
  vulnerabilities/tests/test_improve_runner.py
  vulnerabilities/tests/test_models.py
Labels: 2-next

#1629 Fix 500 error in /api/cpes endpoint
  vulnerabilities/api.py
  vulnerabilities/models.py
  vulnerabilities/tests/test_api.py
  vulnerablecode/settings.py
Labels: bug, 2-next

#1628 Migrate pysec importer to aboutcode pipeline
  vulnerabilities/importers/__init__.py
  vulnerabilities/importers/pysec.py
  vulnerabilities/migrations/0074_update_pysec_advisory_created_by.py
  vulnerabilities/pipelines/pypa_importer.py
  vulnerabilities/pipelines/pysec_importer.py
  vulnerabilities/tests/pipelines/test_pysec_importer_pipeline.py
  vulnerabilities/tests/test_data_migrations.py
Labels: 2-next
