Repository aboutcode-org/vulnerablecode, pull requests merged in 2024-09, with the labels that each got.

#1574 Migrate Npm importer to aboutcode pipeline
  vulnerabilities/importers/__init__.py
  vulnerabilities/improvers/__init__.py
  vulnerabilities/improvers/valid_versions.py
  vulnerabilities/management/commands/import.py
  vulnerabilities/management/commands/improve.py
  vulnerabilities/migrations/0064_update_npm_pypa_advisory_created_by.py
  vulnerabilities/pipelines/__init__.py
  vulnerabilities/pipelines/flag_ghost_packages.py
  vulnerabilities/pipelines/npm_importer.py
  vulnerabilities/pipelines/pypa_importer.py
  vulnerabilities/pipes/advisory.py
  vulnerabilities/tests/pipelines/test_base_pipeline.py
  vulnerabilities/tests/pipelines/test_npm_importer_pipeline.py
  vulnerabilities/tests/pipelines/test_pipeline_id.py
  vulnerabilities/tests/pipes/test_advisory.py
  vulnerabilities/tests/test_changelog.py
  vulnerabilities/tests/test_data/npm/npm-improver-expected.json
  vulnerabilities/tests/test_data/npm/npm_sample.json
  vulnerabilities/tests/test_data/npm/parse-advisory-npm-expected.json
  vulnerabilities/tests/test_data_migrations.py
  vulnerabilities/tests/test_data_source.py
Labels: next

#1599 Use correct regex for CVE
  vulnerabilities/utils.py
Labels: 1-next

#1575 Migrate Nginx importer to aboutcode pipeline
  vulnerabilities/importers/__init__.py
  vulnerabilities/improvers/valid_versions.py
  vulnerabilities/migrations/0065_update_nginx_advisory_created_by.py
  vulnerabilities/models.py
  vulnerabilities/pipelines/nginx_importer.py
  vulnerabilities/pipelines/pypa_importer.py
  vulnerabilities/tests/pipelines/test_nginx_importer_pipeline.py
  vulnerabilities/tests/pipelines/test_pypa_importer_pipeline.py
  vulnerabilities/tests/test_data_migrations.py
Labels: 0-next

#1584 Migrate GitHub importer to aboutcode pipeline
  vulnerabilities/importers/__init__.py
  vulnerabilities/improvers/valid_versions.py
  vulnerabilities/migrations/0067_update_github_advisory_created_by.py
  vulnerabilities/pipelines/__init__.py
  vulnerabilities/pipelines/github_importer.py
  vulnerabilities/tests/pipelines/test_github_importer_pipeline.py
  vulnerabilities/tests/test_data_migrations.py
  vulnerabilities/tests/test_upstream.py
Labels: 1-next

#1587 Migrate NVD importer to aboutcode pipeline
  vulnerabilities/importers/__init__.py
  vulnerabilities/improvers/vulnerability_status.py
  vulnerabilities/migrations/0068_update_nvd_advisory_created_by.py
  vulnerabilities/pipelines/nvd_importer.py
  vulnerabilities/tests/pipelines/test_nvd_importer_pipeline.py
  vulnerabilities/tests/test_data_migrations.py
  vulnerabilities/tests/test_vulnerability_status_improver.py
Labels: 1-next

#1528 Match affected and fixed-by Packages
  vulnerabilities/templates/package_details.html
  vulnerabilities/templates/packages.html
  vulnerabilities/templates/vulnerabilities.html
  vulnerabilities/templates/vulnerability_details.html
  vulnerabilities/templatetags/url_filters.py
  vulnerabilities/tests/test_data/package_sort/input_purls.txt
  vulnerabilities/tests/test_data/package_sort/purls_with_excel_sort.txt
  vulnerabilities/tests/test_data/package_sort/sorted_purls.txt
  vulnerabilities/tests/test_view.py
  vulnerabilities/views.py
  vulnerablecode/static/css/custom.css
Labels: ui, data-quality, 1-next
